### ISSUE TITLE
"Reset" after Import leads to old tape being loaded

### ISSUE THREAD

**Issue by ruptho** [prokls/turingmachine.js#15]
When importing a new turingmachine (and its tape), everything seems to be imported correctly. However, when clicking reset, the tape which existed beforehands is loaded instead of the tape which was last imported. A click on "Load tape" after importing fixes this problem.

Reproduction:
1) Import Machine
2) Click "Run" or "Continue" for a few steps
3) Click Reset
Expectation:
1) Tape is reverted and turingmachine is set to initial state
Observation:
1) Old Tape which existed prior to the import is loaded

**Comment by prokls** [comment]
I agree. That's an issue. Thanks for opening an issue!
